package MusesDrl


global eu.musesproject.server.eventprocessor.correlator.global.StatusGlobal StatusGlobal
global eu.musesproject.server.eventprocessor.correlator.global.Rt2aeGlobal Rt2aeGlobal

import eu.musesproject.server.eventprocessor.correlator.model.owl.AdditionalProtection
import eu.musesproject.server.eventprocessor.correlator.model.owl.AccessRequest
import eu.musesproject.server.eventprocessor.correlator.model.owl.DeviceProtectionEvent
import eu.musesproject.server.eventprocessor.correlator.model.owl.Event
import eu.musesproject.server.eventprocessor.correlator.model.owl.FileObserverEvent
import eu.musesproject.server.eventprocessor.correlator.model.owl.ConnectivityEvent
import eu.musesproject.server.eventprocessor.correlator.model.owl.Clue;
import eu.musesproject.server.eventprocessor.util.Constants
import eu.musesproject.server.risktrust.ThreatOntology
import java.util.ArrayList
import java.util.Date
import java.util.StringTokenizer

declare Event
	@role( event )
	@timestamp ( event_date )
	@expires (1m)
end

declare AccessRequest
	@role( event )
	@timestamp ( event_date )
	@expires (1m)
end

declare ConnectivityEvent
	@role( event )
	@timestamp ( event_date )
	@expires (1m)
end

declare FileObserverEvent
	@role( event )
	@timestamp ( event_date )
	@expires (1m)
end

declare Clue
	@role( event )
	@timestamp ( event_date )
	@expires (1m)
end

declare DeviceProtectionEvent
	@role( event )
	@timestamp ( event_date )
	@expires (1m)
end

declare AdditionalProtection
	@role( event )
	@timestamp ( event_date )
	@expires (1m)
end

rule "Clue-identification-00000"
	no-loop true
	salience 65000
	dialect "mvel"
	when
		e: FileObserverEvent(event=="open_asset", resourceType=="sensitive")
		conn: ConnectivityEvent(bluetoothConnected=="TRUE")
	then
		
		StatusGlobal.log("3.A new clue has been identified, associated to event:"+e.getTimestamp());
		StatusGlobal.log(conn.getBluetoothConnected());		
		StatusGlobal.log("Identifier:"+e.getTimestamp());
		Clue clue = Rt2aeGlobal.composeClue(e,"Bluetooth enabled might turn into data leakage problems",ThreatOntology.DATA_LEAKAGE);
		insert(clue);
	end
	
	rule "Clue-identification-00001"
	no-loop true
	salience 65000
	dialect "mvel"
	when
		e: FileObserverEvent(event=="open_asset", resourceType=="sensitive")
		conn: ConnectivityEvent(wifiEncryption!="WPA2")
	then
		
		StatusGlobal.log("3.A new clue has been identified, associated to event:"+e.getTimestamp());
		StatusGlobal.log(conn.getBluetoothConnected());		
		StatusGlobal.log("Identifier:"+e.getTimestamp());
		Clue clue = Rt2aeGlobal.composeClue(e,"Encryption without WPA2 protocol might be unsecure", ThreatOntology.DATA_LEAKAGE);
		insert(clue);
	end
	
/*rule "Clue-identification-000001"
	no-loop true
	salience 50000
	dialect "mvel"
	when
		request: AccessRequest()
		e: ConnectivityEvent(bluetoothConnected=="TRUE")
		//e: ConnectivityEvent(this before[0,5s] request,bluetoothConnected=="TRUE")		
	then
		
		StatusGlobal.log("3.A new clue has been identified, associated to request:"+request.getId());
		StatusGlobal.log(e.getBluetoothConnected());		
		StatusGlobal.log("AccessRequest identifier:"+request.getId());
		Clue clue = Rt2aeGlobal.composeClue(request,e);
		insert(clue);
	end*/
	
rule "Clue-identification-000002"
	no-loop true
	dialect "mvel"
	when
		original: ConnectivityEvent()
		e: ConnectivityEvent(this after[0,24h] original, bluetoothConnected != original.bluetoothConnected)		
	then		
		StatusGlobal.log("F1:4 Detection of connection properties changes");
		StatusGlobal.addFlag("F1:4");
		//retract(original);
		//retract(e);	
		//TODO: Detect what is the difference between connectivity properties and if it is a DETERIORATION	
	end
	
rule "Clue-identification-000003"
	no-loop true
	dialect "mvel"
	when
		request: AccessRequest()
		conn: ConnectivityEvent(bssid=="AcmeIntranet")		
	then		
		StatusGlobal.log("F1:7 Detection of user connecting to the company intranet");
		StatusGlobal.addFlag("F1:7");
		StatusGlobal.log("AccessRequest identifier:"+request.getId());
		retract(conn);	
	end	

rule "Clue-identification-000004"
	no-loop true
	dialect "mvel"
	when
		fileEvent: FileObserverEvent(path matches ".*confidential.*")	
	then		
		StatusGlobal.log("F2:8 Detection of sensitive info");
		StatusGlobal.addFlag("F2:8");
		//TODO Call a mechanism to infer the sensitivity level of each asset
		retract(fileEvent);	
	end		

rule "Clue-identification-000005"
	no-loop true
	dialect "mvel"
	when
		request: AccessRequest()
		conn: ConnectivityEvent(hiddenSSID==false,wifiNeighbors>50)		
	then		
		StatusGlobal.log("F1:8 Detection of connection to unsecure Wifi. SSID is not hidden and it has "+conn.getWifiNeighbors()+ " neighbors");
		StatusGlobal.addFlag("F1:8");
		StatusGlobal.log("AccessRequest identifier:"+request.getId());	
	end		

rule "Clue-identification-000006"
	no-loop true
	dialect "mvel"
	when
		request: AccessRequest()
		conn: ConnectivityEvent(hiddenSSID==false,wifiConnected==true,wifiEnabled==true)
	then		
		StatusGlobal.log("F2:1 Detection of unsafe communication settings:"+conn.getId());
		StatusGlobal.addFlag("F2:1");	
		StatusGlobal.log("AccessRequest identifier:"+request.getId());
	end
	
			

rule "Clue-identification-000007"
	no-loop true
	dialect "mvel"
	when
		request: AccessRequest()
		conn: ConnectivityEvent(wifiConnected==true,wifiEnabled==true,wifiEncryption=="WPA2")
	then		
		StatusGlobal.log("Unsecure wifi settings:"+conn.getId());
		StatusGlobal.addFlag("DEMO STEP3");	
		StatusGlobal.log("AccessRequest identifier:"+request.getId());
	end	
			
rule "Additional Protection Detection"
	no-loop true
	dialect "mvel"
	when
		request: AccessRequest()
		e: DeviceProtectionEvent()
	then
		StatusGlobal.log("An additional protection event has been detected");
		StatusGlobal.log("AccessRequest identifier:"+request.getId());
		AdditionalProtection protection = Rt2aeGlobal.composeAdditionalProtection(request,e);
		insert(protection);
		StatusGlobal.log("Additional Protection inserted in the WM. AccessRequest identifier:"+request.getId());				
	end	
