
	rule "AccessRequest Detection Save File in a monitored folder"
	no-loop true
	dialect "java"
	when
		e: FileObserverEvent(event=="save_asset")
		not AccessRequest(event=="AccessRequest Detection Save File in a monitored folder")
		
	then
		StatusGlobal.log("1.3.A new AccessRequest has been detected: FileObserverEvent. Type Save File in a Monitored folder");
		Rt2aeGlobal.setStatus(Constants.STARTED);
		StatusGlobal.log("****Event fileobserver****:"+e);
		if(e!=null){
		int id = Rt2aeGlobal.composeAccessRequest(e,"Saving confidential document:"+e.getPath()+"\nYou want to save a confidential document on your device.\nIf you lose your device, other people may be able to access the document.","ALLOW","<path>"+e.getPath()+"</path>");		
		AccessRequest request = new AccessRequest();
		request.setEvent("AccessRequest Detection Save File in a monitored folder");
		StatusGlobal.log("**********"+id);
		StatusGlobal.log("AccessRequest Detection save file type:"+e.getEvent() + " " + e.getTimestamp());
		request.setId(id);
		request.setEvent_date(new Date(System.currentTimeMillis()));
		insert(request);
		////retract(e);
		}else{
		StatusGlobal.log("*****Null object*****");
		}
	end