
	rule "AccessRequest Email without Attachments"
	no-loop true
	dialect "mvel"
	when
		e:EmailEvent(numberAttachments==0)
		not AccessRequest(event=="AccessRequest Email without Attachments")
	then
		StatusGlobal.log("EMAIL DETECTED:"+e.getSubject()+ "Request id:"+ e.getHashId());
		int id = Rt2aeGlobal.composeAccessRequest(e,"Email action allowed","ALLOW", "<noAttachments>0</noAttachments>");
		
		AccessRequest request = new AccessRequest();
		request.setEvent("AccessRequest Email without Attachments");
		StatusGlobal.log("**********"+id);
		request.setId(id);
		request.setEvent_date(new Date(System.currentTimeMillis()));
		insert(request);
	end	
