
rule "AccessRequest Detection open asset type internal unsecure wifi"
	no-loop true
	dialect "java"
	when
		e: FileObserverEvent(event=="open_asset", resourceType=="INTERNAL")
		conn: ConnectivityEvent(wifiConnected==true,wifiEnabled==true, wifiEncryption not matches ".*WPA2.*")
		not AccessRequest(event=="AccessRequest Detection open asset type internal unsecure wifi") 
	then
		StatusGlobal.log("1.1.A new AccessRequest has been detected: FileObserverEvent. Type open-unsecure wifi");
		Rt2aeGlobal.setStatus(Constants.STARTED);
		StatusGlobal.log("****Event conn****:"+conn);
		if((conn!=null)&&(e!=null)){
		int id = Rt2aeGlobal.composeAccessRequest(e,"Opening internal document in unsecure network:"+e.getPath()+"\nYou are connected to an unsecure network and try to open a internal document.\nInformation sent over this network is not encrypted and might be visible to other people can observe. Switch to a secure network.","DENY","<wifiencryption>"+conn.getWifiEncryption()+"</wifiencryption>");
		AccessRequest request = new AccessRequest();
		//request.setEvent(e.getPath());
		request.setEvent("AccessRequest Detection open asset type internal unsecure wifi");
		StatusGlobal.log("**********"+id);
		StatusGlobal.log("AccessRequest Detection open asset type internal:"+e.getEvent() + " " + e.getTimestamp());
		request.setId(id);
		request.setEvent_date(new Date(System.currentTimeMillis()));
		insert(request);
		////retract(e);
		}else{
		StatusGlobal.log("*****Null object*****");
		}
	end

