	rule "AccessRequest Change Security Property-password-protected"
	no-loop true
	dialect "mvel"
	when
		e: ChangeSecurityPropertyEvent(isPasswordProtected==false)
		//d: DeviceProtectionEvent(isPasswordProtected==false)
		not AccessRequest(event=="AccessRequest Change Security Property-password-protected")
	then
		StatusGlobal.log("CHANGE SECURITY PROPERTY 1.4.A new AccessRequest has been detected: ChangeSecurityPropertyEvent.");
		int id = Rt2aeGlobal.composeAccessRequest(e,"Disabling screen lock\nYou are trying to disable screen lock, which is an important security mechanism.\nWithout screen lock, other people with access to your device can obtain sensible data.","DENY", "<isPasswordProtected>false</isPasswordProtected>");
		
		AccessRequest request = new AccessRequest();
		request.setEvent("AccessRequest Change Security Property-password-protected");
		StatusGlobal.log("**********"+id);
		request.setId(id);
		request.setEvent_date(new Date(System.currentTimeMillis()));
		insert(request);

	end