
	rule "Open asset in restricted zone 1"
	no-loop true
	dialect "java"
	when
		e: FileObserverEvent(event=="open_asset", path matches ".*Swe.*", username=="muses")
		e1: LocationEvent(isWithinZone matches ".*1.*")
		not AccessRequest(event=="Open asset in restricted area")
	then
		StatusGlobal.log("Open asset in restricted area");
		Rt2aeGlobal.setStatus(Constants.STARTED);
		if(e!=null){
		int id = Rt2aeGlobal.composeAccessRequest(e,"Accessing file in a restricted area\nYou want to access a file, but you do not have the permission to do so within your current location.\nThe organization\'s security policy doesn\'t allow you to access this file at this zone.","DENY","<path>"+e.getPath()+"</path>");		
		AccessRequest request = new AccessRequest();
		request.setEvent("Open asset in restricted area");
		StatusGlobal.log("**********"+id);
		StatusGlobal.log("AccessRequest Detection open file type:"+e.getEvent() + " " + e.getTimestamp());
		request.setId(id);
		request.setEvent_date(new Date(System.currentTimeMillis()));
		insert(request);
		}else{
		StatusGlobal.log("*****Null object*****");
		}
	end
