
	rule "User entered password"
	no-loop true
	dialect "java"
	when
		e: PasswordEvent()
		not AccessRequest(event=="User entered password")

	then
		StatusGlobal.log("PASSWORD EVENT******************************");
		//Rt2aeGlobal.setStatus(Constants.STARTED);
		if(e!=null){
		int id = Rt2aeGlobal.composeAccessRequest(e,"You just entered a password\nPlease, ensure that you are not being observed.\nIf you are in a public place, somebody could steal your password.","DENY","<packagename>"+e.getPackageName()+"</packagename>");		
		AccessRequest request = new AccessRequest();
		request.setEvent("User entered password");
		StatusGlobal.log("**********"+id);
		request.setId(id);
		request.setEvent_date(new Date(System.currentTimeMillis()));
		insert(request);
		}else{
		StatusGlobal.log("*****Null object*****");
		}

	end
