package eu.musesproject.server.eventprocessor.correlator.engine.changeset;

/*
 * #%L
 * MUSES Server
 * %%
 * Copyright (C) 2013 - 2014 S2 Grupo
 * %%
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * #L%
 */

//
//This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
//See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
//Any modifications to this file will be lost upon recompilation of the source schema. 
//Generated on: 2009.08.03 at 05:05:54 PM CEST 
//

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
* <p>Java class for anonymous complex type.
* 
* <p>The following schema fragment specifies the expected content contained within this class.
* 
* <pre>
* &lt;complexType>
*   &lt;complexContent>
*     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
*       &lt;choice>
*         &lt;element ref="{http://drools.org/drools-5.0/change-set}add"/>
*         &lt;element ref="{http://drools.org/drools-5.0/change-set}remove"/>
*       &lt;/choice>
*     &lt;/restriction>
*   &lt;/complexContent>
* &lt;/complexType>
* </pre>
* 
* 
*/
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
 "add",
 "remove"
})
@XmlRootElement(name = "change-set")
public class ChangeSet {

 protected Add add;
 protected Remove remove;

 /**
  * Gets the value of the add property.
  * 
  * @return
  *     possible object is
  *     {@link Add }
  *     
  */
 public Add getAdd() {
     return add;
 }

 /**
  * Sets the value of the add property.
  * 
  * @param value
  *     allowed object is
  *     {@link Add }
  *     
  */
 public void setAdd(Add value) {
     this.add = value;
 }

 /**
  * Gets the value of the remove property.
  * 
  * @return
  *     possible object is
  *     {@link Remove }
  *     
  */
 public Remove getRemove() {
     return remove;
 }

 /**
  * Sets the value of the remove property.
  * 
  * @param value
  *     allowed object is
  *     {@link Remove }
  *     
  */
 public void setRemove(Remove value) {
     this.remove = value;
 }

}

