package eu.musesproject.server.eventprocessor.correlator.engine.changeset;

/*
 * #%L
 * MUSES Server
 * %%
 * Copyright (C) 2013 - 2014 S2 Grupo
 * %%
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * #L%
 */

//
//This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
//See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
//Any modifications to this file will be lost upon recompilation of the source schema. 
//Generated on: 2009.08.03 at 05:05:54 PM CEST 
//
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
* <p>Java class for anonymous complex type.
* 
* <p>The following schema fragment specifies the expected content contained within this class.
* 
* <pre>
* &lt;complexType>
*   &lt;complexContent>
*     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
*       &lt;attribute name="input-type" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
*       &lt;attribute name="worksheet-name" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
*     &lt;/restriction>
*   &lt;/complexContent>
* &lt;/complexType>
* </pre>
* 
* 
*/
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "decisiontable-conf")
public class DecisiontableConf {

 @XmlAttribute(name = "input-type", required = true)
 @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
 @XmlSchemaType(name = "NCName")
 protected String inputType;
 @XmlAttribute(name = "worksheet-name", required = true)
 @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
 @XmlSchemaType(name = "NCName")
 protected String worksheetName;

 /**
  * Gets the value of the inputType property.
  * 
  * @return
  *     possible object is
  *     {@link String }
  *     
  */
 public String getInputType() {
     return inputType;
 }

 /**
  * Sets the value of the inputType property.
  * 
  * @param value
  *     allowed object is
  *     {@link String }
  *     
  */
 public void setInputType(String value) {
     this.inputType = value;
 }

 /**
  * Gets the value of the worksheetName property.
  * 
  * @return
  *     possible object is
  *     {@link String }
  *     
  */
 public String getWorksheetName() {
     return worksheetName;
 }

 /**
  * Sets the value of the worksheetName property.
  * 
  * @param value
  *     allowed object is
  *     {@link String }
  *     
  */
 public void setWorksheetName(String value) {
     this.worksheetName = value;
 }

}

