package eu.musesproject.server.eventprocessor.correlator.engine.changeset;

/*
 * #%L
 * MUSES Server
 * %%
 * Copyright (C) 2013 - 2014 S2 Grupo
 * %%
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * #L%
 */

//
//This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
//See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
//Any modifications to this file will be lost upon recompilation of the source schema. 
//Generated on: 2009.08.03 at 05:05:54 PM CEST 
//

import javax.xml.bind.annotation.XmlRegistry;


/**
* This object contains factory methods for each 
* Java content interface and Java element interface 
* generated in the com.s2grupo.triton.changeset package. 
* <p>An ObjectFactory allows you to programatically 
* construct new instances of the Java representation 
* for XML content. The Java representation of XML 
* content can consist of schema derived interfaces 
* and classes representing the binding of schema 
* type definitions, element declarations and model 
* groups.  Factory methods for each of these are 
* provided in this class.
* 
*/
@XmlRegistry
public class ObjectFactory {


 /**
  * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.s2grupo.triton.changeset
  * 
  */
 public ObjectFactory() {
 }

 /**
  * Create an instance of {@link Resource }
  * 
  */
 public Resource createResource() {
     return new Resource();
 }

 /**
  * Create an instance of {@link ChangeSet }
  * 
  */
 public ChangeSet createChangeSet() {
     return new ChangeSet();
 }

 /**
  * Create an instance of {@link Add }
  * 
  */
 public Add createAdd() {
     return new Add();
 }

 /**
  * Create an instance of {@link Remove }
  * 
  */
 public Remove createRemove() {
     return new Remove();
 }

 /**
  * Create an instance of {@link DecisiontableConf }
  * 
  */
 public DecisiontableConf createDecisiontableConf() {
     return new DecisiontableConf();
 }

}

